name: backend-deploy-workflow

on:
  push:
    branches: [ "main" ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, GitHub Actions!"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

# steps:
#   - name: Checkout source code
#     uses: actions/checkout@v3

#   - name: Set up JDK 17
#     uses: actions/setup-java@v3
#     with:
#       java-version: '17'

#   - name: Build with Gradle
#     run: ./gradlew clean build -x test

#   - name: Copy file to EC2
#     uses: appleboy/scp-action@v0.1.4
#     with:
#       host: ${{ secrets.EC2_HOST }}
#       username: ${{ secrets.EC2_USER }}
#       key: ${{ secrets.EC2_KEY }}
#       source: "build/libs/bookhub_back-0.0.1-SNAPSHOT.jar"
#       target: "~/bookhub-deploy-backend"

#   - name: Deploy to EC2 (run remote command)
#     uses: appleboy/ssh-action@v1.0.3
#     with:
#       host: ${{ secrets.EC2_HOST }}
#       username: ${{ secrets.EC2_USER }}
#       key: ${{ secrets.EC2_KEY }}
#       script: |
#         pkill -f 'java -jar' || true
#         nohup java -jar ~/bookhub-deploy-backend/bookhub_back-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &
